export const LOGO_LOTTIE_URL = 'https://assets9.lottiefiles.com/packages/lf20_LWQZg8blao.json'
export const GREETING_LOTTIE_URL = 'https://assets9.lottiefiles.com/packages/lf20_xkf2gw3b.json'
export const GREETING_LOTTIE = '/lottie/greeting_lottie.json'
export const LOGO_LOTTIE = '/lottie/logo_lottie.json'
export const HEALTH_LOTTIE = '/lottie/health_lottie.json'
export const BLOOD_BAG_LOTTIE = '/lottie/blood_bag_lottie.json'
export const HEART_PULSE_LOTTIE = '/lottie/heart_pulse_lottie.json'